# Generated by Django 5.0.6 on 2024-05-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contacts_coupons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Coupons',
            new_name='Coupon',
        ),
    ]
