# Generated by Django 5.0.6 on 2024-05-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(default='F:\\shop\\media\\workers_images\\default.jpg', upload_to='workers_images/'),
        ),
    ]
