# Generated by Django 5.0.6 on 2024-05-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
