# Generated by Django 5.0.6 on 2024-05-31 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_cart_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
