# Generated by Django 4.2.1 on 2024-09-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='partners_logo/')),
                ('partner_url', models.URLField()),
            ],
        ),
    ]
