# Generated by Django 4.2.1 on 2024-09-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='partner_name',
            field=models.TextField(default='partner'),
        ),
    ]
