# Generated by Django 5.0.6 on 2024-09-26 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_aboutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutus',
            old_name='content',
            new_name='information',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='title',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='certificate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='name',
            field=models.CharField(default='Welcome to About Us Section', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
