# Generated by Django 5.0.6 on 2024-09-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_content_aboutus_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='certificate',
            field=models.ImageField(upload_to=''),
        ),
    ]
