# Generated by Django 5.0.6 on 2024-09-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_aboutus_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='video_url',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='video',
            field=models.FileField(default='F:\\Уник\\СТРВЕБ\\MWD\\static\x0bideos\\y2meta.com - EPIC INTRO NO TEXT(360p).mp4', upload_to='videos/'),
        ),
    ]
