# Generated by Django 5.0.6 on 2024-11-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_aboutus_video_url_aboutus_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loop', models.BooleanField(default=False)),
                ('navs', models.BooleanField(default=True)),
                ('pags', models.BooleanField(default=True)),
                ('auto', models.BooleanField(default=True)),
                ('stopMouseHover', models.BooleanField(default=False)),
                ('delay', models.PositiveIntegerField(default=5)),
            ],
        ),
    ]
